image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'mysql < .hidden_examples/mysqlsampledatabase.sql'

ports:
  - port: 3306
    onOpen: ignore
    visibility: private
    
